### ISSUE TITLE
Try to build arm64 docker images on macos-github runner

### ISSUE THREAD

**Issue by LtdSauce** [LtdSauce/build-arm64-docker-images-on-macos#1]
# Tried and did not work
- [x] https://github.com/crazy-max/ghaction-setup-docker --> not supported on arm64
- [x] "just" brew install colima && colima start --> does not work because arm64 misses the Hypervisor (https://github.com/abiosoft/colima/issues/1023)
- [x] https://github.com/marketplace/actions/setup-docker --> Emits a warning that it is only available on x86_64

**Comment by LtdSauce** [comment]
The colima error seems to be due to running x64 homebrew or colima on an M1 (which is what i wanted)... but why are they not arm binaries...

Sadly https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#fata0000-error-starting-vm-error-at-starting-exit-status-1 does not mention how to solve this.

**Comment by LtdSauce** [comment]
My current understanding is, that this is not doable. So we'll have to wait until linux/arm64 github runners are available to the public.

**Comment by orhun** [comment]
Thanks for the thorough research! This is unfortunate :/

**Comment by LtdSauce** [comment]
You're welcome! Sorry i couldn't bring up better knews though 😅
